name: Deploy to VPS

on:
  push:
    branches: [main, test-branch]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.VPS_SSH_KEY }}
          
      # - name: Test SSH Connection
      #   run: |
      #     mkdir -p ~/.ssh
      #     echo "${{ secrets.VPS_SSH_KEY }}" > ~/.ssh/deploy_key
      #     chmod 600 ~/.ssh/deploy_key
      #     ssh -o StrictHostKeyChecking=no \
      #         -i ~/.ssh/deploy_key \
      #         ${{ secrets.VPS_USER }}@${{ secrets.VPS_IP }} \
      #         "echo 'SSH connection successful!'"
              
      - name: Deploy Application
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.VPS_IP }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            echo "Starting deployment..."
            if [ -d "space-vivian-ui" ]; then
              cd space-vivian-ui
              git pull
            else
              git clone https://github.com/RusJafar/space-vivian-ui.git
              cd space-vivian-ui
            fi
            docker-compose down
            docker system prune -af
            docker-compose up -d --build
            echo "Deployment completed!"